/**
 * PowerPoint Presentation Adapter
 * 
 * Converts between PowerPoint (.pptx) and UniversalDocument format.
 * Each heading becomes a slide title, content becomes slide body.
 * 
 * Platform Strategy:
 * - All platforms: python-pptx library (Python)
 */

import { BaseOfficeAdapter, OfficeUtils } from "./office-adapter.js";
import { UniversalDocument, DocumentNode, ConversionOptions } from "../document-bridge.js";
import { logger } from "../../utils/logger.js";
import { spawn } from "child_process";

export class PowerPointAdapter extends BaseOfficeAdapter {
  readonly documentType = "powerpoint" as const;
  readonly platform = "cross-platform";
  readonly capabilities = {
    canRead: true,
    canWrite: true,
    canScript: false,
    requiresProcess: true,
  };

  async isAvailable(): Promise<boolean> {
    try {
      await this.runPythonScript("import pptx; print('ok')");
      return true;
    } catch {
      return false;
    }
  }

  protected async doRead(filePath: string, options?: ConversionOptions): Promise<UniversalDocument> {
    const script = `
import pptx
import json
import sys

try:
    prs = pptx.Presentation("${filePath.replace(/\\/g, "\\\\")}")
    nodes = []
    
    for slide_num, slide in enumerate(prs.slides, 1):
        # Extract slide title
        title = ""
        if slide.shapes.title:
            title = slide.shapes.title.text
        
        if title:
            nodes.append({
                "type": "heading",
                "content": title,
                "level": 2
            })
        
        # Extract slide content
        for shape in slide.shapes:
            if shape.has_text_frame and shape != slide.shapes.title:
                text = shape.text_frame.text.strip()
                if text:
                    nodes.append({
                        "type": "paragraph",
                        "content": text
                    })
            
            # Extract tables
            if shape.has_table:
                rows = []
                for row in shape.table.rows:
                    cells = [cell.text for cell in row.cells]
                    rows.append({"cells": cells})
                nodes.append({
                    "type": "table",
                    "content": "Table",
                    "rows": rows
                })
    
    result = {
        "title": prs.slides[0].shapes.title.text if prs.slides and prs.slides[0].shapes.title else "Untitled",
        "nodes": nodes,
        "metadata": {
            "sourceFormat": "pptx",
            "slideCount": len(prs.slides)
        }
    }
    print(json.dumps(result, ensure_ascii=False))
except Exception as e:
    print(json.dumps({"error": str(e)}), file=sys.stderr)
    sys.exit(1)
`;

    const output = await this.runPythonScript(script);
    const data = JSON.parse(output);
    
    if (data.error) throw new Error(data.error);
    
    return {
      title: data.title,
      nodes: data.nodes.map((n: any) => ({
        id: `p-${Math.random().toString(36).slice(2, 8)}`,
        ...n,
      })),
      metadata: data.metadata,
    };
  }

  protected async doWrite(doc: UniversalDocument, filePath: string, options?: ConversionOptions): Promise<void> {
    const sections = OfficeUtils.extractSlideSections(doc.nodes);
    
    const script = `
import pptx
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import json
import sys

try:
    prs = pptx.Presentation()
    
    # Add title slide
    if "${doc.title}" and "${doc.title}" != "Untitled":
        slide_layout = prs.slide_layouts[0]  # Title slide
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = "${doc.title}"
        subtitle.text = "Generated by OpenClaw"
    
    sections = ${JSON.stringify(sections)}
    
    for section in sections:
        slide_layout = prs.slide_layouts[1]  # Title and Content
        slide = prs.slides.add_slide(slide_layout)
        
        # Set title
        title = slide.shapes.title
        title.text = section["title"]
        
        # Add content
        body = slide.placeholders[1]
        tf = body.text_frame
        tf.text = ""
        
        for node in section["content"]:
            if node["type"] == "paragraph":
                p = tf.add_paragraph()
                p.text = node["content"]
                p.level = 0
            elif node["type"] == "list":
                for item in node.get("items", []):
                    p = tf.add_paragraph()
                    p.text = item
                    p.level = 1
            elif node["type"] == "code":
                p = tf.add_paragraph()
                p.text = node["content"]
                p.font.name = "Courier New"
                p.font.size = Pt(12)
    
    # If no sections, add content as bullet points
    if not sections:
        slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        title.text = "${doc.title}"
        
        body = slide.placeholders[1]
        tf = body.text_frame
        for node in ${JSON.stringify(doc.nodes)}:
            if node["type"] == "paragraph":
                p = tf.add_paragraph()
                p.text = node["content"]
    
    prs.save("${filePath.replace(/\\/g, "\\\\")}")
    print("SUCCESS")
except Exception as e:
    print(f"ERROR: {e}", file=sys.stderr)
    sys.exit(1)
`;

    const output = await this.runPythonScript(script);
    if (!output.includes("SUCCESS")) {
      throw new Error(`PowerPoint write failed: ${output}`);
    }
  }

  private runPythonScript(script: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const proc = spawn("python", ["-c", script], {
        env: { ...process.env, PYTHONIOENCODING: "utf-8" },
      });

      let stdout = "";
      let stderr = "";

      proc.stdout.on("data", (data) => {
        stdout += data.toString();
      });

      proc.stderr.on("data", (data) => {
        stderr += data.toString();
      });

      proc.on("close", (code) => {
        if (code !== 0) {
          reject(new Error(stderr || stdout || `Python process exited with code ${code}`));
        } else {
          resolve(stdout.trim());
        }
      });

      proc.on("error", (err) => {
        reject(new Error(`Failed to spawn Python: ${err.message}`));
      });
    });
  }
}
